.PHONY: clean All

All:
	@echo "----------Building project:[ Forca - Debug ]----------"
	@cd "Forca" && "$(MAKE)" -f  "Forca.mk"
clean:
	@echo "----------Cleaning project:[ Forca - Debug ]----------"
	@cd "Forca" && "$(MAKE)" -f  "Forca.mk" clean
